name: Publish Subgraph

description: Verify & publish the subgraph

inputs:
  environment:
    required: true

  subgraph-name:
    required: true

  apollo-key:
    required: true

runs:
  using: "composite"

  steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            **/.yarn
            **/node_modules
            /home/.rover
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2

      - name: Install rover
        shell: bash
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh

      # This returns a non-zero exit code if any of the schema checks fail
      - name: Check subgraph
        shell: bash
        run: |
          APOLLO_TELEMETRY_DISABLED=1 APOLLO_KEY=${{ inputs.apollo-key }} $HOME/.rover/bin/rover subgraph check --name ${{ inputs.subgraph-name }} --schema src/schema.graphql defined-graph@${{ inputs.environment }}

      - name: Publish subgraph
        shell: bash
        run: |
          APOLLO_TELEMETRY_DISABLED=1 APOLLO_KEY=${{ inputs.apollo-key }} $HOME/.rover/bin/rover subgraph publish --name ${{ inputs.subgraph-name }} --schema src/schema.graphql defined-graph@${{ inputs.environment }}




